name: Deploy React to AWS
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: fill envs
        run: >
          echo -e "NODE_ENV=development \n
                   APP_PORT=8080 \n

                   DATABASE_USERNAME=postgres \n
                   DATABASE_PASSWORD=postgres \n
                   DATABASE_NAME=app-db  \n
                   DATABASE_EXTERNAL_PORT=5432 \n
                   DATABASE_HOST=postgres \n
                   #DATABASE_EXTERNAL_PORT=5435 \n
                   #DATABASE_HOST=localhost \n
                   DATABASE_URL_SUPERTOKENS=postgresql://postgres:postgres@postgres:5432/app-db
                   DATABASE_URL_DIRECT=postgresql://postgres:postgres@postgres:5432/app-db
                   DATABASE_URL_SUPERTOKENS=postgresql://postgres:postgres@postgres:5432/app-db \n

                   SUPERTOKENS_EXTERNAL_PORT=3567 \n
                   #DATABASE_HOST=localhost \n
                   SUPERTOKENS_HOST=supertokens \n
                   SUPERTOKENS_URL=http://${SUPERTOKENS_HOST}:${SUPERTOKENS_EXTERNAL_PORT} \n

                   API_URL=http://localhost:8080 \n
                   WEBSITE_URL=http://localhost:3000 \n
                   CLIENT_WEBSITE_URL=http://localhost:3001 \n
                   WEBSITE_DOMAIN=http://localhost \n
          " >> .env && cat .env
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Generate random suffix
        id: random_suffix
        run: echo "RANDOM_SUFFIX=$(uuidgen)" >> $GITHUB_ENV
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: backend
          environment_name: Backend-env
          version_label: ${{ github.sha }}_${{ env.RANDOM_SUFFIX }}
          existing_bucket_name: elasticbeanstalk-eu-central-1-281087710135
          region: eu-central-1
          deployment_package: deploy.zip
